development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: outboxer_developer
  password: outboxer_password
  database: outboxer_development

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: outboxer_developer
  password: outboxer_password
  database: outboxer_test
