development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: outboxer_developer
  password: outboxer_password
  database: outboxer_development
  pool: 6

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: outboxer_developer
  password: outboxer_password
  database: outboxer_test
  pool: 6
