---
:buffer_size: 100
:batch_size: 1000
:buffering_threads_count: 1
:publishing_threads_count: 1
:tick_interval: 0.1
:poll_interval: 5.0
:heartbeat_interval: 5.0
:sweep_interval: 60
:sweep_retention: 60
:sweep_batch_size: 100
:log_level: 1
development:
  :concurrency: 1
staging:
  :concurrency: 10
