name: Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  postgres:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} with PostgreSQL
    strategy:
      matrix:
        ruby:
          - '3.3.0'
    services:
      postgres:
        image: postgres:latest
        env:
          DATABASE_ADAPTER: postgresql
          DATABASE_PORT: 5432
          POSTGRES_USER: outboxer_developer
          POSTGRES_PASSWORD: outboxer_password
          POSTGRES_DB: outboxer_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check PostgreSQL
      run: |
        sudo apt-get -qq install -y postgresql-client
        export PGPASSWORD=outboxer_password
        psql -h localhost -U outboxer_developer -d outboxer_test -c 'SELECT version();'
    - name: Run Database Migrations
      run: RAILS_ENV=test bin/rake outboxer:db:migrate
    - name: Run Tests
      run: RAILS_ENV=test bin/rspec spec

  mysql:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }} with MySQL
    strategy:
      matrix:
        ruby:
          - '3.3.0'
    services:
      mysql:
        image: mysql:latest
        env:
          DATABASE_ADAPTER: mysql2
          DATABASE_PORT: 3306
          MYSQL_ROOT_PASSWORD: outboxer_password
          MYSQL_DATABASE: outboxer_test
          MYSQL_USER: outboxer_developer
          MYSQL_PASSWORD: outboxer_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check MySQL
      run: |
        sudo apt-get -qq install -y mysql-client
        export MYSQL_PWD=outboxer_password
        mysql -h 127.0.0.1 -P 3306 -u outboxer_developer -poutboxer_password outboxer_test -e 'SELECT VERSION();'
    - name: Run Database Migrations
      run: RAILS_ENV=test bin/rake outboxer:db:migrate
    - name: Run Tests
      run: RAILS_ENV=test bin/rspec spec
