name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.2.2'
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: outboxer_tester
          POSTGRES_PASSWORD: outboxer_password
          POSTGRES_DB: outboxer_test
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Check PostgreSQL
      run: |
        sudo apt-get -qq install -y postgresql-client
        export PGPASSWORD=outboxer_password
        psql -h localhost -U outboxer_developer -d outboxer_test -c 'SELECT version();'
    - name: Run Database Migrations
      run: RAILS_ENV=test bin/rake outboxer:db:migrate -f spec/tasks/database.rake
    - name: Run the default task
      run: bundle exec rake
