name: Ruby

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  brakeman:
    runs-on: ubuntu-latest
    name: run brakeman
    steps:
    - uses: actions/checkout@v3
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.6'
        bundler-cache: true
    - name: install brakeman
      run: gem install brakeman
    - name: run brakeman
      run: brakeman --exit-on-warn

  postgres:
    runs-on: ubuntu-latest
    name: run rspec (postgresql)
    strategy:
      matrix:
        ruby:
          - '3.3.6'
    services:
      postgres:
        image: postgres:latest
        env:
          DATABASE_ADAPTER: postgresql
          DATABASE_PORT: 5432
          POSTGRES_USER: outboxer_developer
          POSTGRES_PASSWORD: outboxer_password
          POSTGRES_DB: outboxer_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: check postgresql
      run: |
        sudo apt-get -qq install -y postgresql-client
        export PGPASSWORD=outboxer_password
        psql -h localhost -U outboxer_developer -d outboxer_test -c 'SELECT version();'
    - name: run database migrations
      run: OUTBOXER_ENV=test bin/rake outboxer:db:migrate
    - name: run rspec
      run: OUTBOXER_ENV=test bin/rspec spec

  mysql:
    runs-on: ubuntu-latest
    name: run rspec (mysql)
    strategy:
      matrix:
        ruby:
          - '3.3.6'
    services:
      mysql:
        image: mysql:latest
        env:
          DATABASE_ADAPTER: mysql2
          DATABASE_PORT: 3306
          MYSQL_ROOT_PASSWORD: outboxer_password
          MYSQL_DATABASE: outboxer_test
          MYSQL_USER: outboxer_developer
          MYSQL_PASSWORD: outboxer_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
    steps:
    - uses: actions/checkout@v3
    - name: set up ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: check mySQL
      run: |
        sudo apt-get -qq install -y mysql-client
        export MYSQL_PWD=outboxer_password
        mysql -h 127.0.0.1 -P 3306 -u outboxer_developer -poutboxer_password outboxer_test -e 'SELECT VERSION();'
    - name: run database migrations
      env:
        OUTBOXER_ENV: test
        DATABASE_ADAPTER: mysql2
        DATABASE_HOST: 127.0.0.1
        DATABASE_PORT: 3306
      run: |
        bin/rake outboxer:db:migrate
    - name: run rspec
      env:
        OUTBOXER_ENV: test
        DATABASE_ADAPTER: mysql2
        DATABASE_PORT: 3306
        DATABASE_HOST: 127.0.0.1
      run: bin/rspec spec

  # accountify_tests:
  #   runs-on: ubuntu-latest
  #   name: Run Accountify Lifecycle Test
  #   steps:
  #   - uses: actions/checkout@v3
  #   - name: Set up Ruby
  #     uses: ruby/setup-ruby@v1
  #     with:
  #       ruby-version: '3.3.6'
  #   - name: Clone Accountify Repository and Set Up Outboxer
  #     run: |
  #       git clone git@github.com:fast-programmer/accountify_app.git
  #       cd accountify_app
  #       echo "gem 'outboxer', git: 'https://github.com/fast-programmer/outboxer.git', branch: 'master'" >> Gemfile
  #       bundle install
  #       bin/rails g outboxer:schema
  #       bin/rake db:migrate
  #       bin/rails db:setup
  #       bin/rake outboxer:db:seed
  #       bin/rails g outboxer:sidekiq_publisher
  #       echo "
  #       class Event < ActiveRecord::Base
  #         after_create do |event|
  #           Outboxer::Message.queue(messageable: event)
  #         end
  #       end
  #       " > app/models/event.rb
  #   - name: Publish Messages
  #     run: |
  #       cd accountify_app
  #       echo "
  #       Outboxer::Publisher.publish do |message|
  #         case message[:messageable_type]
  #         when 'Event'
  #           puts \"Message published for Event \#{message[:messageable_id]}\"
  #         end
  #       end
  #       " > script/publish_messages.rb
  #       bundle exec ruby script/publish_messages.rb
  #   - name: Create Event and Verify Outboxer
  #     run: |
  #       cd accountify_app
  #       bin/rails runner "Event.create!"
  #   - name: Run Accountify Lifecycle Test
  #     run: |
  #       cd accountify_app
  #       bundle exec ruby script/accountify/invoice/test_lifecycle.rb
